### ISSUE TITLE
ANALISE "DONE"4 https://github.com/vivus-plataforma/vivus-plataforma.github.io-repository/issues/65#issue-2677851827: NÃO ADIMITIDA

### ISSUE THREAD

**Issue by eliziersantos** [vivus-plataforma/vivus-plataforma.github.io-repository#105]
O AGENDAMENTO É FEITO NA TELA ANTERIOR

@eliziersantos Ainda com problema, @eliziersantos e @will-brandsi 

https://github.com/vivus-plataforma/vivus-plataforma.github.io-repository/issues/65#issue-2677851827

1- Agendamento de Post
Não consegui agendar um post

![Image](https://github.com/user-attachments/assets/80ae9b3c-4ba5-4e38-9065-5040283973ac)

**Comment by Michelle-Mello** [comment]
@eliziersantos @will-brandsi 
Ainda não foi possivel agendar posts
Favor admitir o Draft

**Comment by Joilson-Rangel** [comment]
@will-brandsi @eliziersantos @luisfmatheuscorrea na homologação de 07/12 foi evidenciado que o agendamento de postagem de video ainda não está funcionando. 

https://github.com/user-attachments/assets/4bc3b024-3cff-469c-b9a1-6f2f1dc54bd4

**Comment by luisfmatheuscorrea** [comment]
Validar no iPhone, Android Funcionando!

**Comment by luisfmatheuscorrea** [comment]
Validação deverá ser feita na próxima Release.
