### ISSUE TITLE
ANALISE "DONE" 1 vivus-plataforma/vivus-plataforma.github.io-repository#44 (comment): NÃO ADIMITIDA

### ISSUE THREAD

**Issue by eliziersantos** [vivus-plataforma/vivus-plataforma.github.io-repository#108]
A FUNCIONALIDADE DE LOCALIZAÇÃO NÃO FOI REMOVIDA DA VERSÃO EM DEFINIÇÃO CONJUNTA COM A ÀREA DE PRODUTO.

Ainda com problema, @eliziersantos e @will-brandsi 

https://github.com/vivus-plataforma/vivus-plataforma.github.io-repository/issues/44#issue-2660445183

1- Tela de CRIAÇÃO DE POST não apresenta campo para inserir localização nem opção de marcar pessoas
![Image](https://github.com/user-attachments/assets/0a3770cf-fd3d-4c05-926e-b57136ae7f55)

2- Tela PREVIEW DO POST
Não apresenta o video escolhido para postagem
Não tem a opção CANCELAR
Ao clicar no botão POSTAR nada acontece
![Image](https://github.com/user-attachments/assets/44b57bec-7daa-4e2d-bed1-005d306532c1)

3- Tela VIEW DO POST
O post não aparece no feed do perfil do usuário
![Image](https://github.com/user-attachments/assets/90f7ddb0-a1fb-415b-b997-000dc2004cb6)

**Comment by Michelle-Mello** [comment]
@eliziersantos @will-brandsi 
ainda nao é possivel postar video e foto
Favor admitir o draft

**Comment by Joilson-Rangel** [comment]
@will-brandsi @eliziersantos @luisfmatheuscorrea na homologação de 07/12 foi evidenciado que ainda não é possível postar VIDEOS. Remover sobreposição de áudio.

https://github.com/user-attachments/assets/75ebf726-b3df-4ca3-bae9-c7000bc46e81

**Comment by luisfmatheuscorrea** [comment]
Resolvido!
