### ISSUE TITLE
ANALISE "DONE" 3 https://github.com/vivus-plataforma/vivus-plataforma.github.io-repository/issues/63#issue-2677849339

### ISSUE THREAD

**Issue by eliziersantos** [vivus-plataforma/vivus-plataforma.github.io-repository#110]
Ainda com problema, @eliziersantos e @will-brandsi 

https://github.com/vivus-plataforma/vivus-plataforma.github.io-repository/issues/63#issue-2677849339

Tela PREVIEW
1- O vídeo selecionado não aparece na visualização do preview
2- Falta o botão CANCELAR
![Image](https://github.com/user-attachments/assets/2b024dd9-dc7b-42f0-9330-0ee570267fd7)

**Comment by luisfmatheuscorrea** [comment]
Resolvido!
