### ISSUE TITLE
ANALISE "DONE" 5 https://github.com/vivus-plataforma/vivus-plataforma.github.io-repository/issues/61#issue-2677845388: DEBUG & CORREÇÃO

### ISSUE THREAD

**Issue by eliziersantos** [vivus-plataforma/vivus-plataforma.github.io-repository#111]
https://github.com/vivus-plataforma/vivus-plataforma.github.io-repository/issues/61#issue-2677845388

Post CRIAR
1- Não consegui criar post de imagem. O aplicativo ficou rodando a tela de criação, não direcionou para a tela do preview
![Image](https://github.com/user-attachments/assets/a0732c17-ad89-4c05-a109-fcc8de58fecb)

2- Não consegui criar post de video. O aplicativo direciona para a tela do preview, mas o video selecionado não aparece e ao clicar no botão para postar, fica rodando e não sai dessa tela
![Image](https://github.com/user-attachments/assets/d99a633b-fc1c-4fcc-baff-93728ec4352c)

**Comment by luisfmatheuscorrea** [comment]
Resolvido!
