### ISSUE TITLE
ANÁLISE "NO SECRETO" 1 (27_11): Ferramenta de busca não funciona

### ISSUE THREAD

**Issue by eliziersantos** [vivus-plataforma/vivus-plataforma.github.io-repository#122]
Busca por palavra chave não funciona

**Comment by eliziersantos** [comment]
@luisfmatheuscorrea O serviço event/findNearest na API está pronto, só aplicar

**Comment by luisfmatheuscorrea** [comment]
@eliziersantos mandar a data que não está vindo, e do jeito q vem no próprio get event

**Comment by eliziersantos** [comment]
@luisfmatheuscorrea feito

**Comment by luisfmatheuscorrea** [comment]
Resolvido!
