### ISSUE TITLE
ANÁLISE "NO SECRETO" 2 (27_11): Botões: compartilhar, três pontos e salvar não funcionam

### ISSUE THREAD

**Issue by eliziersantos** [vivus-plataforma/vivus-plataforma.github.io-repository#123]
![Image](https://github.com/user-attachments/assets/ea356c14-6e89-447a-b1c4-fd9ef928bc3b)

**Comment by eliziersantos** [comment]
Estas funcionalidades nao foram definidas as telas de fluxo no figma.

**Comment by Michelle-Mello** [comment]
@eliziersantos @will-brandsi @Joilson-Rangel 
Favor analisar a implementação das funcionalidades, pois estão definidas no fluxo do FIGMA para a primeira versão
![Image](https://github.com/user-attachments/assets/70660588-dff7-4f36-9d1f-46c321fe941c)
