### ISSUE TITLE
ANÁLISE "NO SECRETO" 4 (27_11): Os botões: Close Caption, Encaminhar e Salvar não estão funcionando

### ISSUE THREAD

**Issue by eliziersantos** [vivus-plataforma/vivus-plataforma.github.io-repository#125]
https://github.com/user-attachments/assets/e59c60f1-2b45-4188-8acb-fcde6e9b144f

**Comment by eliziersantos** [comment]
Estas funcionalidades nao foram definidas as telas de fluxo no figma.

**Comment by Michelle-Mello** [comment]
@eliziersantos @will-brandsi @Joilson-Rangel 
Favor analisar

As funcionalidades estão definidas no Figma desde o inicio do projeto
![Image](https://github.com/user-attachments/assets/2cbd8ad6-466d-494e-926c-75beb3fa9e1a)
![Image](https://github.com/user-attachments/assets/94f28cea-acca-4ea1-9b0f-2dfac0573d60)
