### ISSUE TITLE
ANÁLISE "NO SECRETO" 5 (27_11): Título errado

### ISSUE THREAD

**Issue by eliziersantos** [vivus-plataforma/vivus-plataforma.github.io-repository#126]
Título errado:

1) Título do aplicativo: 

![Image](https://github.com/user-attachments/assets/74b86bec-f34e-472a-a8bd-075c969ae2fe)

2) Titulo do figma: 

![Image](https://github.com/user-attachments/assets/2e61b36f-7d6c-4ebb-846c-f2c17d674b1b)

**Comment by luisfmatheuscorrea** [comment]
Resolvido!
