### ISSUE TITLE
ANÁLISE "NO SECRETO" 6 (27_11): Frases no aplicativo diferentes do figma

### ISSUE THREAD

**Issue by eliziersantos** [vivus-plataforma/vivus-plataforma.github.io-repository#127]
De acordo com o figma, as frases corretas para os campos assinalados a seguir seriam: 
- Crie sua sala de oração: tema, data e hora. 
- Vamos orar por...

1) tela do aplicativo: 

![Image](https://github.com/user-attachments/assets/4c74acf2-c567-4360-83f0-87229728a13a)

2) tela do figma: 

![Image](https://github.com/user-attachments/assets/901d7701-474b-48fd-8668-e95f5bc73215)

**Comment by luisfmatheuscorrea** [comment]
Resolvido!
