### ISSUE TITLE
ANÁLISE "NO SECRETO 7 (27_11): Tela de acesso a Sala no Secreto em desacordo com o figma

### ISSUE THREAD

**Issue by eliziersantos** [vivus-plataforma/vivus-plataforma.github.io-repository#128]
A tela de acesso a Sala do Secreto está totalmente diferente do figma

1) tela do aplicativo: 

![Image](https://github.com/user-attachments/assets/824e99cd-b577-438d-8f0e-133295ba1320)

2) tela do figma: 

![Image](https://github.com/user-attachments/assets/cd8cc6bf-c3d4-4d06-a449-3335e10a926d)

**Comment by luisfmatheuscorrea** [comment]
Mesma questao do que foi tratado na issue #94

**Comment by Michelle-Mello** [comment]
@eliziersantos @will-brandsi @Joilson-Rangel 

Estou aguardando novo link para homologar se a tarefa foi concluida
