### ISSUE TITLE
ANALISE "DONE"14 (03.12) CORRIGIR FOTO DO PERFIL VIVUS https://github.com/vivus-plataforma/vivus-plataforma.github.io-repository/issues/68#issue-2684764035

### ISSUE THREAD

**Issue by eliziersantos** [vivus-plataforma/vivus-plataforma.github.io-repository#131]
A imagem com a logomarca da empresa em alta qualidade não foi incluida na foto do perfil
![Image](https://github.com/user-attachments/assets/b8669464-3edf-4e0e-b253-e1fc52498629)

**Comment by eliziersantos** [comment]
@Joilson-Rangel por favor solicite ao design a imagem que deve ser utilizada para atender esta solicitação e anexe aqui na issue para que a correção possa ser aplicada

**Comment by luisfmatheuscorrea** [comment]
Mesmo caso do #113
