### ISSUE TITLE
ANALISE "DONE" 1(03.12) SALA NO SECRETO CRIAR https://github.com/vivus-plataforma/vivus-plataforma.github.io-repository/issues/93#issue-2691145510

### ISSUE THREAD

**Issue by eliziersantos** [vivus-plataforma/vivus-plataforma.github.io-repository#132]
Ajustar o icone da tela conforme o figma (é um microfone e não uma camera) 
![Image](https://github.com/user-attachments/assets/202e6246-15d6-4b5c-ab43-e1909865816a)

**Comment by luisfmatheuscorrea** [comment]
Resolvido!

**Comment by Michelle-Mello** [comment]
@eliziersantos @will-brandsi @Joilson-Rangel 
Estou aguardando um novo link para homologar a conclusão da tarefa
