### ISSUE TITLE
ANALISE "DONE"2 (03.12) SALA NO SECRETO CRIAR https://github.com/vivus-plataforma/vivus-plataforma.github.io-repository/issues/93#issue-2691145510

### ISSUE THREAD

**Issue by eliziersantos** [vivus-plataforma/vivus-plataforma.github.io-repository#133]
Não consegui criar uma Sala no Secreto
Problemas encontrados:
O aplicativo não aceitou colocar a data de hoje (03.12)
Ao selecionar a hora o aplicativo fechou

Abaixo, segue o video da tentativa
https://github.com/user-attachments/assets/f12b5bb6-ebba-41b8-ae8d-940458972273

**Comment by luisfmatheuscorrea** [comment]
Analisar no iPhone, pois no Android está funcionando e não foi possível replicar o erro.
