### ISSUE TITLE
ANALISE "DONE"4 (03.12) SALA NO SECRETO PARTICIPAR https://github.com/vivus-plataforma/vivus-plataforma.github.io-repository/issues/95#issue-2691154421

### ISSUE THREAD

**Issue by eliziersantos** [vivus-plataforma/vivus-plataforma.github.io-repository#134]
A tela para escolher uma Sala e poder participar não mostra as Salas agendadas 
Essa tela esta diferente da tela do Figma

Como esta a Tela no Aplicativo:
![Image](https://github.com/user-attachments/assets/db9adcc4-364d-4f93-80de-1d152c1119c3)

Como deve ser a tela no Figma:
![Image](https://github.com/user-attachments/assets/fed0287f-49d1-4127-88b4-56bbd1edd6bc)

**Comment by luisfmatheuscorrea** [comment]
Acredito que nao há salas, testei aqui e está funcionando normal.

**Comment by Michelle-Mello** [comment]
@eliziersantos @will-brandsi @Joilson-Rangel 
Estou aguardando um novo link para homologar se a tarefa foi concluida
