### ISSUE TITLE
ANALISE "DONE"5 (03.12) MOMENTO UNICO CRIAR https://github.com/vivus-plataforma/vivus-plataforma.github.io-repository/issues/98#issue-2691237393

### ISSUE THREAD

**Issue by eliziersantos** [vivus-plataforma/vivus-plataforma.github.io-repository#135]
Eu criei uma Live e agendei para o dia 05/12 as 9:00H
Porem, na tela inicial a Live que eu programei aparece agendada para o dia 5/12 as 12:00H

Tela com a criação da Live para 9:00h
![Image](https://github.com/user-attachments/assets/c5eaf36a-967b-4b71-9aa4-4fe74629106b)

Tela Principal mostrando a Live programada para 12:00h
![Image](https://github.com/user-attachments/assets/50e5492e-b7c3-4275-9398-cc4af7342219)

**Comment by eliziersantos** [comment]
@luisfmatheuscorrea ajustar a exibição da data levando em consideração o GMT+3

**Comment by luisfmatheuscorrea** [comment]
Você tem que mandar a data como GMT - 3, porque o certo é vir dai, devido motivos até, de exibição ou não do item na tela. @eliziersantos
