### ISSUE TITLE
ANALISE "DONE" 7 (03.12) REDE SOCIAL https://github.com/vivus-plataforma/vivus-plataforma.github.io-repository/issues/48#issue-2660482310

### ISSUE THREAD

**Issue by eliziersantos** [vivus-plataforma/vivus-plataforma.github.io-repository#136]
A tela de post esta sem a funcionalidade para compartilhar e exibir comentarios
 A Tela apresentada no aplicativo
![Image](https://github.com/user-attachments/assets/9b0a4b66-609f-4feb-8f5d-ba40c84468fb)

 A tela apresentada no Figma
![Image](https://github.com/user-attachments/assets/8d60d51c-a065-4305-977f-c4fdd5e6ac01)

**Comment by SGARB77** [comment]
O que teremos nessa versão?

Sergio
*Garb *-
*www.studio77.online*
-
011 95833 4706


Em ter., 3 de dez. de 2024 às 22:05, Elizier ***@***.***>
escreveu:

**Comment by Joilson-Rangel** [comment]
Conforme mostrado na última reunião (04/12) de acompanhamento de cronograma, a funcionalidade "compartilhar" sempre esteve previsto no figma. Conforme também conversamos nessa mesma reunião, o @luisfmatheuscorrea ficará responsável por incluir a funcionalidade compartilhar post dentro do aplicativo, conforme combinado com a área de design @SGARB77 . Compartilhamento de qualquer outra coisa dentro do aplicativo ou para fora dele, ficarão para fases posteriores. Favor remover o DONE e endereçar essa tarefa para FRONTEND.

**Comment by Joilson-Rangel** [comment]
REGISTRO: definido em reunião de 06/12 entre @Michelle-Mello @SGARB77 e @luisfmatheuscorrea que todos os botões de COMPARTILHAR do aplicativo farão o compartilhamento externo através da criação de links com a foto original da postagem.

**Comment by luisfmatheuscorrea** [comment]
Adicionado os botões, somente funcionalidade de compartilhamento está sendo terminada!
