### ISSUE TITLE
ANALISE "DONE"8 (03.12) TELA EDITAR PERFIL https://github.com/vivus-plataforma/vivus-plataforma.github.io-repository/issues/80#issue-2690497461

### ISSUE THREAD

**Issue by eliziersantos** [vivus-plataforma/vivus-plataforma.github.io-repository#137]
Inserir o uso do TAB para criara linhas na Descrição da Bio  não foi realizada. Esta diferente da Tela descrita no fluxo do Figma

Tela do Figma
![Image](https://github.com/user-attachments/assets/7b684ea3-4b6a-44da-9377-02234c605151)

Descrição contínua da Bio, sem possibilidade de criar linhas
![Image](https://github.com/user-attachments/assets/0117048e-d90b-4f88-bd9d-308a62d2ae03)
![Image](https://github.com/user-attachments/assets/02f93dfd-d9d5-43f9-8dee-3088207fcf0d)

**Comment by luisfmatheuscorrea** [comment]
Resolvido, inserido a possibilidade de dar Enter e descer a linha.
