### ISSUE TITLE
ANALISE "DONE"9 EDITAR PERFIL  (03.12) https://github.com/vivus-plataforma/vivus-plataforma.github.io-repository/issues/87#issue-2690556881

### ISSUE THREAD

**Issue by eliziersantos** [vivus-plataforma/vivus-plataforma.github.io-repository#140]
Ajuste da foto do perfil não foi corrigido, conforme mostra o video abaixo
https://github.com/user-attachments/assets/f48637e1-4161-4365-8dbb-b38a7e2c7a7d

**Comment by luisfmatheuscorrea** [comment]
Isso é questao de ajuste do usuário no recorte, foi adicionado a ferramenta de recorte para se ter noçao daonde ficaria cada parte da imagem.

**Comment by Michelle-Mello** [comment]
@eliziersantos @will-brandsi @Joilson-Rangel 

Favor analisar a demanda, pois a foto do usuário ainda fica "desenquadrada" no perfil (parece que dá um zoom e destorce a imagem)

**Comment by luisfmatheuscorrea** [comment]
Fiz os testes e está enquadrando, tanto no Android e no iPhone (que poderia ser o que não estava)
