### ISSUE TITLE
ANALISE "DONE"10 EDITAR PERFIL (03.12) https://github.com/vivus-plataforma/vivus-plataforma.github.io-repository/issues/88#issue-2690561123

### ISSUE THREAD

**Issue by eliziersantos** [vivus-plataforma/vivus-plataforma.github.io-repository#141]
Ajuste da foto de perfil não foi realizado, conforme mostra o video abaixo
https://github.com/user-attachments/assets/15df0ef2-e95b-4df8-98d3-fbd3e9602f20

**Comment by luisfmatheuscorrea** [comment]
Não é o sistema que ajusta, e sim o usuário, por isso há o crop, para que o usuário perceba e resolva o ajuste.
