### ISSUE TITLE
ANALISE "DONE"17 (03.12) https://github.com/vivus-plataforma/vivus-plataforma.github.io-repository/issues/45#issue-2660445686

### ISSUE THREAD

**Issue by eliziersantos** [vivus-plataforma/vivus-plataforma.github.io-repository#142]
Não é possivel visualizar os versiculos que foram salvos (ao clicar no versiculo, o texto nao aparece)
 https://github.com/user-attachments/assets/72bfac14-70f1-4dac-a9ce-ee3eabbf4c81

**Comment by eliziersantos** [comment]
Não foi especificado do figma o fluxo de exibir um versículo salvo. @SGARB77 @will-brandsi @Joilson-Rangel definirem se a funcionalidade será implementada neste momento

**Comment by luisfmatheuscorrea** [comment]
Resolvido!
