### ISSUE TITLE
ANALISE "DONE"16 BIBLIA https://github.com/vivus-plataforma/vivus-plataforma.github.io-repository/issues/45#issue-2660445686

### ISSUE THREAD

**Issue by eliziersantos** [vivus-plataforma/vivus-plataforma.github.io-repository#143]
Não é possivel selecionar os versiculos ao clicar na funcionalidade, conforme o video abaixo
https://github.com/user-attachments/assets/96906967-c604-4318-ad29-b71e6e275b48

**Comment by luisfmatheuscorrea** [comment]
Resolvido!
