### ISSUE TITLE
ANALISE "DONE"11 POST VIEW (03.12) https://github.com/vivus-plataforma/vivus-plataforma.github.io-repository/issues/64#issue-2677850008

### ISSUE THREAD

**Issue by eliziersantos** [vivus-plataforma/vivus-plataforma.github.io-repository#146]
Não foi possivel criar um post
Ao clicar no botao o aplicativo fica rodando e o post não é publicado, conforme você pode ver no video abaixo
https://github.com/user-attachments/assets/c40f0a41-36d7-4351-a3f3-9c82255131ee

**Comment by luisfmatheuscorrea** [comment]
Resolvido!
