### ISSUE TITLE
NEW (07_12): CRIAR POST: ao publicar um post ele não aparece no feed principal do aplicativo

### ISSUE THREAD

**Issue by eliziersantos** [vivus-plataforma/vivus-plataforma.github.io-repository#150]
No feed principal devem aparecer os posts de todos os usuários. 

Atualmente os posts que os usuários publicam só aparecem no feed do próprio usuário. 

No feed principal do aplicativo somente visualizamos publicações da VIVUS, quando na verdade deveria conter as publicações de TODOS os usuários. 

https://github.com/user-attachments/assets/1ffc2124-e4bb-47fb-a139-7db310cfb8c7

**Comment by luisfmatheuscorrea** [comment]
@eliziersantos parece que ai no back está adicionando +3 horas, eu já mando como GMT normal

**Comment by eliziersantos** [comment]
Foram feitos tunnings nas consultas e podem ser necessários mais tunnings
