### ISSUE TITLE
NEW 9 (07_12): CRIAR POST: tela branca ao visualizar o post

### ISSUE THREAD

**Issue by eliziersantos** [vivus-plataforma/vivus-plataforma.github.io-repository#153]
Ao criar um post de foto e entrar no feed do usuário para visualizar o post, ao clicar em cima da postagem aparece uma tela branca que impede qq outro comando. 

https://github.com/user-attachments/assets/c6db9b3d-aafa-48c7-882d-abc3c653d0a2

**Comment by luisfmatheuscorrea** [comment]
Resolvido!
