### ISSUE TITLE
NEW (07_12): POST sem a opção de botão de COMPARTILHAR

### ISSUE THREAD

**Issue by eliziersantos** [vivus-plataforma/vivus-plataforma.github.io-repository#155]
O POST está vindo com a opção LIKE e SALVAR, mas faltando a opção COMPARTILHAR (lembrando que, conforme combinado, essa primeira versão vai permitir somente o compartilhamento de links com imagens original do post). Favor incluir a opção COMPARTILHAR, conforme identificação visual do figma. 

![Image](https://github.com/user-attachments/assets/01280bd0-5e9e-4d77-b7a5-19668412f4bd)

**Comment by luisfmatheuscorrea** [comment]
Botões foram adicionados!
