### ISSUE TITLE
NEW (07_12): MOMENTO ÚNICO: problemas com data e horário de agendamento

### ISSUE THREAD

**Issue by eliziersantos** [vivus-plataforma/vivus-plataforma.github.io-repository#156]
Ao tentar agendar uma live de Momento Único a data e horário aparecem na tela principal de agendamento diferentes do originalmente digitado. 

Vídeo mostrando Momento Único criado para as 21:00 do dia 08/12 e aparecendo na tela principal de agendamento como sendo as 00:00 do dia 09/12. 

https://github.com/user-attachments/assets/1d17520d-cbbb-431a-aca7-bcf227d9fa51

**Comment by eliziersantos** [comment]
@luisfmatheuscorrea ao exibir a hora deve-se colocar a location GMT+3

**Comment by luisfmatheuscorrea** [comment]
@eliziersantos parece que ai no back está adicionando +3 horas, eu já mando como GMT normal

**Comment by luisfmatheuscorrea** [comment]
Resolvido
