### ISSUE TITLE
NEW (07.12) BOTÕES DE REDE SOCIAL excluir

### ISSUE THREAD

**Issue by eliziersantos** [vivus-plataforma/vivus-plataforma.github.io-repository#157]
@will-brandsi @eliziersantos @luisfmatheuscorrea 

Na tela de exibição do Perfil do Usuário, favor excluir os botões de Rede Social (vamos usar somente na versão 2)
![Image](https://github.com/user-attachments/assets/01f0aa54-150d-47ac-b7bd-330400ff3032)

**Comment by luisfmatheuscorrea** [comment]
Retirado!
