### ISSUE TITLE
NEW (07.12) GRID DE POSTAGEM Alinhamento do layout dos posts

### ISSUE THREAD

**Issue by eliziersantos** [vivus-plataforma/vivus-plataforma.github.io-repository#158]
@will-brandsi @eliziersantos @luisfmatheuscorrea 

Realizar alinhamento no Grid (feed) de postagem do usuário
Os posts estão desalinhados no feed do usuário
https://github.com/user-attachments/assets/6242929d-678f-4c5f-a156-0923181f2705

**Comment by luisfmatheuscorrea** [comment]
Resolvido!
