### ISSUE TITLE
ANALISE "DONE"8 (05.12) e (07.12) BUSCA https://github.com/vivus-plataforma/vivus-plataforma.github.io-repository/issues/119#issue-2702460004

### ISSUE THREAD

**Issue by eliziersantos** [vivus-plataforma/vivus-plataforma.github.io-repository#161]
@eliziersantos @will-brandsi @Joilson-Rangel 

Favor analisar o comentario de que a demanda não foi concluida
https://github.com/vivus-plataforma/vivus-plataforma.github.io-repository/issues/119#issuecomment-2521219057

@eliziersantos, favor classificar item (Front ou Back End, prioridade). 

@will-brandsi , @eliziersantos , @luisfmatheuscorrea na análise de 07/12 foi evidenciado que ainda persiste o bug ao tentar realizar uma busca por post (o aplicativo fecha), conforme mostra o video abaixo. 

https://github.com/user-attachments/assets/fc8212b5-aab7-4274-81ce-2c8af3c35a6d

**Comment by luisfmatheuscorrea** [comment]
Resolvido!
