### ISSUE TITLE
ANALISE "DONE" 1 (05.12) MOMENTO UNICO TELA ESTAMOS AO VIVO https://github.com/vivus-plataforma/vivus-plataforma.github.io-repository/issues/100#issue-2691242195

### ISSUE THREAD

**Issue by eliziersantos** [vivus-plataforma/vivus-plataforma.github.io-repository#162]
@eliziersantos @will-brandsi @Joilson-Rangel 
Favor analisar o comentario de que a tarefa não foi concluida
https://github.com/vivus-plataforma/vivus-plataforma.github.io-repository/issues/100#issuecomment-2520838992

@will-brandsi @eliziersantos 

REGISTRO: Combinado em reunião de 06/12 entre @Michelle-Mello @SGARB77 e @luisfmatheuscorrea que os novos templates das telas para participação ao vivo do Momento Único e Sala do Secreto não terão foto de fundo para permitir a inserção de foto dos eventos. Os novos templates serão enviado ao FRONTEND pelo DESIGNER.

**Comment by luisfmatheuscorrea** [comment]
Feito!
