### ISSUE TITLE
ANALISE "DONE"7 BOTÕES AGENDA SALA NO SECRETO https://github.com/vivus-plataforma/vivus-plataforma.github.io-repository/issues/123#issue-2702460934

### ISSUE THREAD

**Issue by eliziersantos** [vivus-plataforma/vivus-plataforma.github.io-repository#164]
@eliziersantos @will-brandsi @Joilson-Rangel 

Favor analisar o comentario de que a demanda não foi concluida e estava prevista para essa primeira versão
https://github.com/vivus-plataforma/vivus-plataforma.github.io-repository/issues/123#issuecomment-2521085083

@will-brandsi @eliziersantos 

REGISTRO: definido em reunião de 06/12 entre @Michelle-Mello @SGARB77 e @luisfmatheuscorrea que:

1) os botões de COMPARTILHAR da SALA DO SECRETO e MOMENTO ÚNICO farão o compartilhamento externo através da criação de links com a foto original da postagem.

2) os botões de OPÇÕES (três pontinhos na vertical) da SALA DO SECRETO e MOMENTO ÚNICO serão excluídos; 

3) os botões de SALVAR da SALA DO SECRETO e MOMENTO ÚNICO será usado para criação de pop up como lembrete para o usuário.

**Comment by luisfmatheuscorrea** [comment]
Removido o botão de opções

**Comment by luisfmatheuscorrea** [comment]
Os botões estão colocados no lugar, só o Compartilhar que está sendo terminado, lembrete está pronto.
