### ISSUE TITLE
ANALISE 2 (12.12) BIBLIA Ao clicar no Livro de Jó aparece o texto do livro de  João

### ISSUE THREAD

**Issue by eliziersantos** [vivus-plataforma/vivus-plataforma.github.io-repository#177]
@will-brandsi @eliziersantos @luisfmatheuscorrea 

https://github.com/user-attachments/assets/dcd7e0ab-b703-4035-bc05-47e44a46e17a

**Comment by luisfmatheuscorrea** [comment]
Resolvido!
