### ISSUE TITLE
CADERNO DE TESTES III (19_12): Funcionalidade microfone

### ISSUE THREAD

**Issue by eliziersantos** [vivus-plataforma/vivus-plataforma.github.io-repository#202]
Erro No Secreto e Momento Único

Necessário conjugar permissão de fala dada pelo host ao participante com a abertura do microfone.

Sugestão de solução dada pelo Elizier: mensagem de call back para o aplicativo do participante para liberação do microfone. 

Mensagem para o aplicativo do participante comandando desligar o microfone. 

Ajustar sincronismo de mensagens de comando de call back entre host e participantes. 

VIncular à issue #200

**Comment by luisfmatheuscorrea** [comment]
Problema é real é o levantar a mão, a parte de microfone e fala já está ocorrendo normalmente.
