### ISSUE TITLE
CADERNO DE TESTES IV (22_12): Imagem de boas vindas

### ISSUE THREAD

**Issue by eliziersantos** [vivus-plataforma/vivus-plataforma.github.io-repository#219]
@SGARB77 enviar imagem VIVUS de boas vindas aos novos usuários

**Comment by bilxxx** [comment]
Imagem de boas-vindas para o App @eliziersantos @luisfmatheuscorrea 

![Imagem de boas-vindas](https://github.com/user-attachments/assets/213fd9a6-8b4d-4753-8025-ad0619e3afd8)
