### ISSUE TITLE
CADERNO DE TESTES VII (28_12): Botão "desacompanhar" sobrepondo informações

### ISSUE THREAD

**Issue by Joilson-Rangel** [vivus-plataforma/vivus-plataforma.github.io-repository#235]
@gtorrespcode e @SGARB77 Design enviará uma arte para essa correção

![Image](https://github.com/user-attachments/assets/ecec591e-9091-4a05-8719-f5461f30c975)

**Comment by bilxxx** [comment]
Ajuste finalizado - Segue a imagem para visualização abaixo.

Todos os arquivos estão no figma.

![Image](https://github.com/user-attachments/assets/7e213b7e-0168-40c9-b9cb-db938e216fbb)
![Image](https://github.com/user-attachments/assets/04e67e64-774c-4b35-88a6-ff74cf05f00c)

**Comment by bilxxx** [comment]
Os textos devem ser "ACOMPANHAR" e "ACOMPANHANDO" quando já estiver seguindo a pessoa. Não usaremos "DESACOMPANHAR". @luisfmatheuscorrea
