### ISSUE TITLE
POST

### ISSUE THREAD

**Issue by eliziersantos** [vivus-plataforma/vivus-plataforma.github.io-repository#44]
## DESCRIÇÃO

Reconstruir tela de POST de acordo com o layout e fluxo estabelecido no figma

1. Tela de criação/edição de Post:  mvp-20241114-0.0.3 
### Issue(s) de destino: https://github.com/vivus-plataforma/vivus-plataforma.github.io-repository/issues/61

![Image](https://github.com/user-attachments/assets/de847eaa-5fd6-40ce-8234-9c74c43578bd)

2. Tela de Agendamento de post:  mvp-20241118-0.0.4 
![Image](https://github.com/user-attachments/assets/3a39f0f3-4393-4281-b693-ee832c635352)

3. Tela de  Preview de post:  mvp-20241118-0.0.4 
![Image](https://github.com/user-attachments/assets/dc623c17-676e-415a-9a11-67bc12b45912)

4. Tela de View do post:  mvp-20241120-0.0.5 
### Issue(s) de destino: https://github.com/vivus-plataforma/vivus-plataforma.github.io-repository/issues/64

![Image](https://github.com/user-attachments/assets/a6af73ad-9248-4b38-846a-ee041950f406)
![Image](https://github.com/user-attachments/assets/5fd9c2f8-5fce-45a0-8480-46b7a4127046)
![Image](https://github.com/user-attachments/assets/417b0a0c-a560-4783-9b8d-a2bdd20f35dc)
![Image](https://github.com/user-attachments/assets/80175289-294c-4cbb-9b66-66e848626cd1)

5. Serviço batch de disparo de posts agendados:  mvp-20241120-0.0.5

**Comment by eliziersantos** [comment]
Observar as demandas:

https://github.com/orgs/vivus-plataforma/projects/17?pane=issue&itemId=86624757

CROP DE IMAGEM

![Image](https://github.com/user-attachments/assets/43d3c316-fe52-4510-8de0-9697418a51a6)

**Comment by eliziersantos** [comment]
Observar da demanda: 

https://github.com/orgs/vivus-plataforma/projects/17?pane=issue&itemId=86390876

**Comment by Michelle-Mello** [comment]
@eliziersantos @will-brandsi @Joilson-Rangel 

Criado novo draft para reportar que a publicação de posts (foto e video) não esta funcionando
Estou aguardando novo link para homologar a conclusão dessa demanda
