### ISSUE TITLE
Sala no Secreto

### ISSUE THREAD

**Issue by eliziersantos** [vivus-plataforma/vivus-plataforma.github.io-repository#53]
## DESCRIÇÃO
```
Revisar fluxo da Sala no Secreto
```
https://github.com/vivus-plataforma/vivus-plataforma.github.io-repository/issues/53
1. Criar "Sala no Secreto": ### Issue(s) de destino https://github.com/vivus-plataforma/vivus-plataforma.github.io-repository/issues/93
![Image](https://github.com/user-attachments/assets/a5a62c41-93f0-42f0-a367-b0f1e2f0e776)

2. View "Sala no Secreto": ### Issue(s) de destino https://github.com/vivus-plataforma/vivus-plataforma.github.io-repository/issues/94
![Image](https://github.com/user-attachments/assets/bd69be2b-45fd-4ee7-a56c-2c7f1ea11f53)

3. Participar "Sala no Secreto": ### Issue(s) de destino https://github.com/vivus-plataforma/vivus-plataforma.github.io-repository/issues/95
![Image](https://github.com/user-attachments/assets/967044c9-d0ae-4f93-acb2-3186e53ff324)
 
4. Temporizar: ### Issue(s) de destino https://github.com/vivus-plataforma/vivus-plataforma.github.io-repository/issues/96
tempo de audiolive, avisar que vai acabar exibindo o temporizador e, fechar a sala.

**Comment by eliziersantos** [comment]
Observar as demandas:

https://github.com/orgs/vivus-plataforma/projects/17?pane=issue&itemId=86622677
https://github.com/orgs/vivus-plataforma/projects/17?pane=issue&itemId=86622297

**Comment by eliziersantos** [comment]
@SGARB77 

Observe que esta demanda está programada para a versão mvp-20241122-0.0.6

**Comment by eliziersantos** [comment]
@Joilson-Rangel vc tem alguma observação?

**Comment by eliziersantos** [comment]
@luisfmatheuscorrea Verificar

**Comment by luisfmatheuscorrea** [comment]
Resolvido!
