### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by eliziersantos** [vivus-plataforma/vivus-plataforma.github.io-repository#58]
1. https://github.com/orgs/vivus-plataforma/projects/17?pane=issue&itemId=86624933

Resolvido pois já está ocultando o teclado

2. https://github.com/orgs/vivus-plataforma/projects/17?pane=issue&itemId=86624995
Verificar mensagem de erro que permanece sendo exibida na próxima tela

**Comment by eliziersantos** [comment]
Ainda falta resolver o item 2

**Comment by luisfmatheuscorrea** [comment]
Resolvido!
