### ISSUE TITLE
corrigir a foto do perfil VIVUS: CONTEÚDO

### ISSUE THREAD

**Issue by eliziersantos** [vivus-plataforma/vivus-plataforma.github.io-repository#68]
![Image](https://github.com/user-attachments/assets/83ab00f9-2d1e-495f-881e-8dab31350ec1)

**Comment by eliziersantos** [comment]
Incluir foto para o usuario VIVUS

**Comment by Michelle-Mello** [comment]
@eliziersantos @will-brandsi @Joilson-Rangel 

@eliziersantos por favor me informe o email e senha usados para o  login do perfil VIVUS (eu vou trocar a foto do perfil, editar  para corrigir as informações da Bio e testar novas postagens de conteudo)

**Comment by Michelle-Mello** [comment]
@Joilson-Rangel @eliziersantos @will-brandsi 

segue a foto para ser usada no perFil da VIVUS

estou aguardando o email de ![Image](https://github.com/user-attachments/assets/cd1b1b2f-bf7a-4868-8148-65af66ff5b9c)
login e a senha dessa conta de usuário
