### ISSUE TITLE
Erros no view do POST: DEBUG & CORREÇÃO

### ISSUE THREAD

**Issue by eliziersantos** [vivus-plataforma/vivus-plataforma.github.io-repository#71]
Ao clicar em um post que o conteúdo seja vídeo a tela fica estática conforme exemplificado abaixo.

![Image](https://github.com/user-attachments/assets/1de8458c-f680-44d6-9cb6-d182bf0e5595)
![Image](https://github.com/user-attachments/assets/480aca51-079d-4120-b2b8-d226064660a2)
![Image](https://github.com/user-attachments/assets/bbf6369a-7f66-4b11-92a6-0b0e45057531)

**Comment by luisfmatheuscorrea** [comment]
Resolvido!
