### ISSUE TITLE
Tela de editar perfil (erro 8)(ANÁLISE-15): VERIFICAR FIGMA & CORREÇÃO

### ISSUE THREAD

**Issue by eliziersantos** [vivus-plataforma/vivus-plataforma.github.io-repository#77]
O Perfil do Usuário mostra os icones nas outras redes sociais acompanhadas dos respectivos nomes de usuários, dispostos na direção vertical. Apesar de diferente do figma, isto pode ser mantido assim. No entanto, é preciso que se dê um maior espaçamento entre eles (muito embolado/agrupado) e ao clicar nos icones não há um direcionamento para as outras redes. 

1) Tela do aplicativo: 

![Image](https://github.com/user-attachments/assets/9b71bbd4-b12e-4894-aae5-2fee0049a119)

2) Tela do figma: 

![Image](https://github.com/user-attachments/assets/9f01e65b-79b4-4062-b793-db13cf019484)

**Comment by luisfmatheuscorrea** [comment]
Resolvido
