### ISSUE TITLE
Tela de editar perfil (erro 5)(ANÁLISE-12 ): DEBUG & CORREÇÃO

### ISSUE THREAD

**Issue by eliziersantos** [vivus-plataforma/vivus-plataforma.github.io-repository#79]
Ao tentar editar o número do telefone, inesperadamente apareceu a mensagem a seguir sobre gênero/sexo, sendo necessário fechar o aplicativo, pois não foi possível retornar a tela anterior. 

Tela do aplicativo: 

![Image](https://github.com/user-attachments/assets/dd724932-8e20-47af-9f7a-1c54bee9965c)

**Comment by luisfmatheuscorrea** [comment]
Resolvido!
