### ISSUE TITLE
Tela de editar perfil (erro 6)(ANÁLISE-13): ANALISE de FIGMA & CORREÇÃO

### ISSUE THREAD

**Issue by eliziersantos** [vivus-plataforma/vivus-plataforma.github.io-repository#80]
O campo "Sua Bio" não permite o uso de tab para pular linha e, por isso, a descrição acaba sobrepondo a engrenagem de configuração. Favor configurar para permitir pular linha, conforme previsto no figma. 

Tela do aplicativo: 

![Image](https://github.com/user-attachments/assets/fe143913-38aa-4246-ab95-9fccf571ceef)

Tela do figma: 

![Image](https://github.com/user-attachments/assets/a1971f90-1f33-46f6-bc4d-8a07616fadf9)

**Comment by luisfmatheuscorrea** [comment]
Resolvido!

**Comment by Michelle-Mello** [comment]
@eliziersantos @will-brandsi @Joilson-Rangel 

Favor rever o status de concluido, pois ainda não temos a opção para criar linhas no momento de escrever a Bio

1- A Bio com texto corrido, sem linhas
![Image](https://github.com/user-attachments/assets/72a475c0-b242-4ac5-b7fe-3e39720f78d8)

2- A Bio com linhas, conforme planejado no FIGMA
![Image](https://github.com/user-attachments/assets/aa2545a7-e89d-4c43-a264-dbdd98aa8904)
