### ISSUE TITLE
ANÁLISE-4 (24_11): Texto de TERMOS DE USO, POLITICA DE PRIVACIDADE e SOBRE

### ISSUE THREAD

**Issue by eliziersantos** [vivus-plataforma/vivus-plataforma.github.io-repository#81]
Os textos de TERMOS DE USO, POLÍTICA DE PRIVACIDADE e SOBRE devem apresentar o texto em tela cheia conforme figma.

1) Tela do aplicativo

![Image](https://github.com/user-attachments/assets/9e7ae836-d4b5-463a-bc41-62b4200086e2)

2) Tela do figma

![Image](https://github.com/user-attachments/assets/6d81b37d-3596-4da7-ba0d-0c7085ed70a8)

**Comment by eliziersantos** [comment]
Alterar alinhamento de html e campo na tela

**Comment by eliziersantos** [comment]
Resolvido

**Comment by Michelle-Mello** [comment]
@eliziersantos @will-brandsi @Joilson-Rangel 

Estou aguardando um novo link para homologar se essa demanda foi concluida
