### ISSUE TITLE
Batente da tela de Preferências do Usuário(ANÁLISE-6): ANÁLISE & CORREÇÃO de LAYOUT

### ISSUE THREAD

**Issue by eliziersantos** [vivus-plataforma/vivus-plataforma.github.io-repository#82]
A tela de Preferências do Usuário ao ser movimentada para cima, se sobrepõe as informações de hora, nível de bateria, etc. É necessário criar um limite/batente, como feito por outros aplicativos (ex: Instagram). 

1) Tela do aplicativo: 

![Image](https://github.com/user-attachments/assets/8240ec8d-bcdd-487f-a893-03ff44b52fe7)

2) Tela do Instagram

![Image](https://github.com/user-attachments/assets/84a51010-c6ae-4166-ac04-d713200b2ec2)

**Comment by luisfmatheuscorrea** [comment]
Resolvido!
