### ISSUE TITLE
Erro durante o cadastro(ANÁLISE-3 ): DEBUB & CORREÇÃO

### ISSUE THREAD

**Issue by eliziersantos** [vivus-plataforma/vivus-plataforma.github.io-repository#83]
Na tela de SOBRE, ao abrir o link do MANIFESTO e depois tentar voltar para a TELA ANTERIOR, o aplicativo retornou para a tela de cadastro e apresentou um erro informado que o usuário já estava cadastrado. 

Mensagem de erro: 

![Image](https://github.com/user-attachments/assets/741a4eb4-78f3-4e20-b24c-df7641aaa471)

**Comment by luisfmatheuscorrea** [comment]
Resolvido!
