### ISSUE TITLE
Tela de preferências do usuário(ANÁLISE-5): REMOVER O CAMPO DA TELA

### ISSUE THREAD

**Issue by eliziersantos** [vivus-plataforma/vivus-plataforma.github.io-repository#85]
O aplicativo continua mostrando a mostrando a frase " O que você pode oferecer?" sem opções. Essa frase/pergunta deve ser removida.

Tela do aplicativo: 

![Image](https://github.com/user-attachments/assets/9a850d60-7cd0-44d7-b236-747fec9a893e)

**Comment by luisfmatheuscorrea** [comment]
Resolvido!
