### ISSUE TITLE
Tela de editar perfil (erro 1)(ANÁLISE-8): ANÁLISE & CORREÇÃO

### ISSUE THREAD

**Issue by eliziersantos** [vivus-plataforma/vivus-plataforma.github.io-repository#87]
Algumas fotos selecionadas para perfil não ficam centralizadas no aplicativo. 

Tela do aplicativo: 

![Image](https://github.com/user-attachments/assets/82bb39b9-183f-478a-8680-fa092bc26ce2)

**Comment by luisfmatheuscorrea** [comment]
Resolvido!

**Comment by Michelle-Mello** [comment]
@eliziersantos @will-brandsi @Joilson-Rangel 

A demanda ainda não foi concluida, a imagem continua extrapolando as bordas da tela 

Necessidade correção já reportada anteriormente

https://github.com/user-attachments/assets/5d700470-0c07-428f-aee9-fdd8e83d7281
