### ISSUE TITLE
Tela de editar perfil (erro 4)(ANÁLISE-11): CORREÇÃO

### ISSUE THREAD

**Issue by eliziersantos** [vivus-plataforma/vivus-plataforma.github.io-repository#89]
No campo "Seu telefone > Número" o aplicativo já traz um número pré preenchido. Favor remover ou substituir por (00) 00000 0000

Tela do aplicativo: 

![Image](https://github.com/user-attachments/assets/7b95ac82-05b8-4310-a02e-23d35b263024)

**Comment by luisfmatheuscorrea** [comment]
Testei aqui e não vem preenchido, somente vem preenchido qnd vc já altera, mas a primeira vez não vem não.
