### ISSUE TITLE
REDE SOCIAL: Seguir

### ISSUE THREAD

**Issue by eliziersantos** [vivus-plataforma/vivus-plataforma.github.io-repository#90]
### Issue(s) de origem
|REPOSITÓRIO|ISSUE|
|--|--|
|[vivus-plataforma.github.io-repository](https://github.com/vivus-plataforma/vivus-plataforma.github.io-repository)|[#48](https://github.com/vivus-plataforma/vivus-plataforma.github.io-repository/issues/48)|

## DESCRIÇÃO
```
Verificar se é possível: 
SEGUIR
DEIXAR DE SEGUIR
BLOQUEAR SEGUIDOR
```

**Comment by luisfmatheuscorrea** [comment]
Teste feito, porém para o "BLOQUEAR SEGUIDOR", deve ser feito um teste maior.
