### ISSUE TITLE
REDE SOCIAL: Like

### ISSUE THREAD

**Issue by eliziersantos** [vivus-plataforma/vivus-plataforma.github.io-repository#91]
### Issue(s) de origem
|REPOSITÓRIO|ISSUE|
|--|--|
|[vivus-plataforma.github.io-repository](https://github.com/vivus-plataforma/vivus-plataforma.github.io-repository)|[#48](https://github.com/vivus-plataforma/vivus-plataforma.github.io-repository/issues/48)|

## DESCRIÇÃO
```
Verificar se é possível: 
DAR LIKE
SABER QUEM DEU O LIKE
QUANTIDADE DE LIKES
EXIBIR ANIMAÇÃO DE LIKE
```

**Comment by luisfmatheuscorrea** [comment]
Verificado que é possível dar Like, porem não há UI (Design) para Saber quem deu like e quantos likes tem o post. e a animação terá que ser revista. @eliziersantos

**Comment by luisfmatheuscorrea** [comment]
Implementar na próxima versão a visualização dessas informações.
