### ISSUE TITLE
REDE SOCIAL: Comentar

### ISSUE THREAD

**Issue by eliziersantos** [vivus-plataforma/vivus-plataforma.github.io-repository#92]
### Issue(s) de origem
|REPOSITÓRIO|ISSUE|
|--|--|
|[vivus-plataforma.github.io-repository](https://github.com/vivus-plataforma/vivus-plataforma.github.io-repository)|[#48](https://github.com/vivus-plataforma/vivus-plataforma.github.io-repository/issues/48)|

## DESCRIÇÃO
```
Verificar se é possível: 
COMENTAR
SABER A QUANTIDADE DE COMENTÁRIO
SABER QUEM COMENTOU
```

**Comment by luisfmatheuscorrea** [comment]
Testado Comentar e Saber quem comentou. Porém para a quantidade não há UI (Design) para isso.

**Comment by luisfmatheuscorrea** [comment]
Implementar na próxima versão a visualização dessas informações.
