### ISSUE TITLE
MOMENTO ÚNICO: Agendar

### ISSUE THREAD

**Issue by eliziersantos** [vivus-plataforma/vivus-plataforma.github.io-repository#99]
### ISSUE de ORIGEM: https://github.com/vivus-plataforma/vivus-plataforma.github.io-repository/issues/54

1. Tela de agendamento
![Image](https://github.com/user-attachments/assets/ad7d2a99-5281-4424-8dec-2c82850e7d20)

**Comment by luisfmatheuscorrea** [comment]
Resolvido!
